version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      # build and push Docker image
      - run: |
          TAG=latest
          docker build -t ganbaranob1/tf-gan:$TAG .
          echo $DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push ganbaranob1/tf-gan:$TAG
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master